version: '3'

services:
  guestbook:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./data:/usr/src/app/data
    container_name: guestbook-web